# cemm-gen makeparam --smiles "CC" --resname BLA --description "Blank group" --overwrite ;
# cemm-gen makeparam --smiles "CCC" --resname MTY --description "Methyl group" --overwrite ;
# cemm-gen makeparam --smiles "CCCC" --resname ETY --description "Ethyl group" --overwrite ;
# cemm-gen makeparam --smiles "CCO" --resname HYD --description "Hydroxy group" --overwrite ;
# cemm-gen makeparam --smiles "CC=O" --resname CBO --description "Carbonyl group" --overwrite ;
# cemm-gen makeparam --smiles "CCOC" --resname MTO --description "Methoxy group" --overwrite ;
# cemm-gen makeparam --smiles "CCc1ccccc1" --resname ARM --description "Aromatic group" --overwrite ;
# cemm-gen makeparam --smiles "CCc1ccc(O)cc1" --resname ARO --description "Tyrosine-like group" --overwrite ;
# cemm-gen makeparam --smiles "CCC(:O):O" --resname NEG --description "Negatively charged carboxy group" --netcharge -1 --no-neutralize --overwrite ;
# cemm-gen makeparam --smiles "CCC(=O)O" --resname CBX --description "Carboxy group" --overwrite ;
# cemm-gen makeparam --smiles "CCC[NH3+]" --resname POS --description "Positively charged amino group" --netcharge 1 --no-neutralize --overwrite ;
# cemm-gen makeparam --smiles "CCCN" --resname AMO --description "Amino group" --overwrite ;
# cemm-gen makeparam --smiles "CCS" --resname THI --description "Thiol group" --overwrite ;
# cemm-gen makeparam --smiles "CC[S-]" --resname THE --description "Thiolate group" --netcharge -1 --no-neutralize --overwrite ;
# cemm-gen makeparam --smiles "CCSC" --resname MTI --description "Methionine group" --overwrite ;
# cemm-gen makeparam --smiles "CCNC(N)N" --resname GUA --description "Guanidino group" --overwrite ;